include(CPM)

# Can't be under 'executorch-src' for some reason
# https://github.com/pytorch/executorch/issues/6475
# CPMAddPackage(
#   URI
#   "gh:pytorch/executorch@1.0.1"
#   OPTIONS
#   "EXECUTORCH_BUILD_EXTENSION_TENSOR ON"
#   "EXECUTORCH_BUILD_EXTENSION_FLAT_TENSOR ON"
#   "EXECUTORCH_BUILD_EXTENSION_DATA_LOADER ON"
#   "EXECUTORCH_BUILD_EXTENSION_MODULE ON"
#   "EXECUTORCH_BUILD_EXTENSION_NAMED_DATA_MAP ON"
#   "EXECUTORCH_BUILD_KERNELS_OPTIMIZED ON"
#   "EXECUTORCH_BUILD_XNNPACK ON"
#   "EXECUTORCH_XNNPACK_ENABLE_KLEIDI ON")

set(EXECUTORCH_BUILD_EXTENSION_TENSOR ON)
set(EXECUTORCH_BUILD_EXTENSION_FLAT_TENSOR ON)
set(EXECUTORCH_BUILD_EXTENSION_DATA_LOADER ON)
set(EXECUTORCH_BUILD_EXTENSION_MODULE ON)
set(EXECUTORCH_BUILD_EXTENSION_NAMED_DATA_MAP ON)
set(EXECUTORCH_BUILD_KERNELS_OPTIMIZED ON)
set(EXECUTORCH_BUILD_XNNPACK ON)
set(EXECUTORCH_XNNPACK_ENABLE_KLEIDI ON)

add_subdirectory("third-party/executorch")

CPMAddPackage(
  URI
  "gh:jarro2783/cxxopts@3.3.1"
  OPTIONS
  "CXXOPTS_BUILD_EXAMPLES OFF"
  "CXXOPTS_BUILD_TESTS OFF"
  "CXXOPTS_ENABLE_INSTALL ON"
  "CXXOPTS_ENABLE_WARNINGS ON")
